<<<<<<< HEAD
# Generated by Django 6.0 on 2026-01-10 06:54
=======
# Generated by Django 6.0 on 2026-01-07 14:12
>>>>>>> 02f82937dad22993b12d55292de4307ff018b07e

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('publication_year', models.IntegerField()),
            ],
        ),
    ]
